//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Option: light framework (CF/Silverlight) enabled
    
// Generated from: OpenApiMessages.proto
// Note: requires additional types generated from: OpenApiModelMessages.proto
// Note: requires additional types generated from: CommonModelMessages.proto
namespace OpenApiLib.Proto
{
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAAuthReq")]
  public partial class ProtoOAAuthReq : global::ProtoBuf.IExtensible
  {
    public ProtoOAAuthReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_AUTH_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private string _clientId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"clientId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string clientId
    {
      get { return _clientId; }
      set { _clientId = value; }
    }
    private string _clientSecret;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"clientSecret", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string clientSecret
    {
      get { return _clientSecret; }
      set { _clientSecret = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAAuthRes")]
  public partial class ProtoOAAuthRes : global::ProtoBuf.IExtensible
  {
    public ProtoOAAuthRes() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_AUTH_RES; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOASubscribeForTradingEventsReq")]
  public partial class ProtoOASubscribeForTradingEventsReq : global::ProtoBuf.IExtensible
  {
    public ProtoOASubscribeForTradingEventsReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_SUBSCRIBE_FOR_TRADING_EVENTS_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private long _accountId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private string _accessToken;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"accessToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accessToken
    {
      get { return _accessToken; }
      set { _accessToken = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOASubscribeForTradingEventsRes")]
  public partial class ProtoOASubscribeForTradingEventsRes : global::ProtoBuf.IExtensible
  {
    public ProtoOASubscribeForTradingEventsRes() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_SUBSCRIBE_FOR_TRADING_EVENTS_RES; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAUnsubscribeFromTradingEventsReq")]
  public partial class ProtoOAUnsubscribeFromTradingEventsReq : global::ProtoBuf.IExtensible
  {
    public ProtoOAUnsubscribeFromTradingEventsReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_UNSUBSCRIBE_FROM_TRADING_EVENTS_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private long _accountId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAUnsubscribeFromTradingEventsRes")]
  public partial class ProtoOAUnsubscribeFromTradingEventsRes : global::ProtoBuf.IExtensible
  {
    public ProtoOAUnsubscribeFromTradingEventsRes() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_UNSUBSCRIBE_FROM_TRADING_EVENTS_RES; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAGetSubscribedAccountsReq")]
  public partial class ProtoOAGetSubscribedAccountsReq : global::ProtoBuf.IExtensible
  {
    public ProtoOAGetSubscribedAccountsReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_GET_SUBSCRIBED_ACCOUNTS_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAGetSubscribedAccountsRes")]
  public partial class ProtoOAGetSubscribedAccountsRes : global::ProtoBuf.IExtensible
  {
    public ProtoOAGetSubscribedAccountsRes() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_GET_SUBSCRIBED_ACCOUNTS_RES; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<long> _accountId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> accountId
    {
      get { return _accountId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAExecutionEvent")]
  public partial class ProtoOAExecutionEvent : global::ProtoBuf.IExtensible
  {
    public ProtoOAExecutionEvent() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_EXECUTION_EVENT; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private ProtoOAExecutionType _executionType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"executionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAExecutionType executionType
    {
      get { return _executionType; }
      set { _executionType = value; }
    }
    private ProtoOAOrder _order;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoOAOrder order
    {
      get { return _order; }
      set { _order = value; }
    }
    private ProtoOAPosition _position = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoOAPosition position
    {
      get { return _position; }
      set { _position = value; }
    }
    private string _reasonCode;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"reasonCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string reasonCode
    {
      get { return _reasonCode?? ""; }
      set { _reasonCode = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool reasonCodeSpecified
    {
      get { return this._reasonCode != null; }
      set { if (value == (this._reasonCode== null)) this._reasonCode = value ? this.reasonCode : (string)null; }
    }
    private bool ShouldSerializereasonCode() { return reasonCodeSpecified; }
    private void ResetreasonCode() { reasonCodeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOACreateOrderReq")]
  public partial class ProtoOACreateOrderReq : global::ProtoBuf.IExtensible
  {
    public ProtoOACreateOrderReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_CREATE_ORDER_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private string _accessToken;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accessToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accessToken
    {
      get { return _accessToken; }
      set { _accessToken = value; }
    }
    private long _accountId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private string _symbolName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"symbolName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbolName
    {
      get { return _symbolName; }
      set { _symbolName = value; }
    }
    private ProtoOAOrderType _orderType;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"orderType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAOrderType orderType
    {
      get { return _orderType; }
      set { _orderType = value; }
    }
    private ProtoTradeSide _tradeSide;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"tradeSide", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTradeSide tradeSide
    {
      get { return _tradeSide; }
      set { _tradeSide = value; }
    }
    private long _volume;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long volume
    {
      get { return _volume; }
      set { _volume = value; }
    }
    private int? _relativeStopLossInPips;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"relativeStopLossInPips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int relativeStopLossInPips
    {
      get { return _relativeStopLossInPips?? default(int); }
      set { _relativeStopLossInPips = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool relativeStopLossInPipsSpecified
    {
      get { return this._relativeStopLossInPips != null; }
      set { if (value == (this._relativeStopLossInPips== null)) this._relativeStopLossInPips = value ? this.relativeStopLossInPips : (int?)null; }
    }
    private bool ShouldSerializerelativeStopLossInPips() { return relativeStopLossInPipsSpecified; }
    private void ResetrelativeStopLossInPips() { relativeStopLossInPipsSpecified = false; }
    
    private int? _relativeTakeProfitInPips;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"relativeTakeProfitInPips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int relativeTakeProfitInPips
    {
      get { return _relativeTakeProfitInPips?? default(int); }
      set { _relativeTakeProfitInPips = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool relativeTakeProfitInPipsSpecified
    {
      get { return this._relativeTakeProfitInPips != null; }
      set { if (value == (this._relativeTakeProfitInPips== null)) this._relativeTakeProfitInPips = value ? this.relativeTakeProfitInPips : (int?)null; }
    }
    private bool ShouldSerializerelativeTakeProfitInPips() { return relativeTakeProfitInPipsSpecified; }
    private void ResetrelativeTakeProfitInPips() { relativeTakeProfitInPipsSpecified = false; }
    
    private double? _baseSlippagePrice;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"baseSlippagePrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double baseSlippagePrice
    {
      get { return _baseSlippagePrice?? default(double); }
      set { _baseSlippagePrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool baseSlippagePriceSpecified
    {
      get { return this._baseSlippagePrice != null; }
      set { if (value == (this._baseSlippagePrice== null)) this._baseSlippagePrice = value ? this.baseSlippagePrice : (double?)null; }
    }
    private bool ShouldSerializebaseSlippagePrice() { return baseSlippagePriceSpecified; }
    private void ResetbaseSlippagePrice() { baseSlippagePriceSpecified = false; }
    
    private long? _slippageInPips;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"slippageInPips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long slippageInPips
    {
      get { return _slippageInPips?? default(long); }
      set { _slippageInPips = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool slippageInPipsSpecified
    {
      get { return this._slippageInPips != null; }
      set { if (value == (this._slippageInPips== null)) this._slippageInPips = value ? this.slippageInPips : (long?)null; }
    }
    private bool ShouldSerializeslippageInPips() { return slippageInPipsSpecified; }
    private void ResetslippageInPips() { slippageInPipsSpecified = false; }
    
    private double? _limitPrice;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"limitPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double limitPrice
    {
      get { return _limitPrice?? default(double); }
      set { _limitPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool limitPriceSpecified
    {
      get { return this._limitPrice != null; }
      set { if (value == (this._limitPrice== null)) this._limitPrice = value ? this.limitPrice : (double?)null; }
    }
    private bool ShouldSerializelimitPrice() { return limitPriceSpecified; }
    private void ResetlimitPrice() { limitPriceSpecified = false; }
    
    private double? _stopPrice;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"stopPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double stopPrice
    {
      get { return _stopPrice?? default(double); }
      set { _stopPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool stopPriceSpecified
    {
      get { return this._stopPrice != null; }
      set { if (value == (this._stopPrice== null)) this._stopPrice = value ? this.stopPrice : (double?)null; }
    }
    private bool ShouldSerializestopPrice() { return stopPriceSpecified; }
    private void ResetstopPrice() { stopPriceSpecified = false; }
    
    private long? _expirationTimestamp;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"expirationTimestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long expirationTimestamp
    {
      get { return _expirationTimestamp?? default(long); }
      set { _expirationTimestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool expirationTimestampSpecified
    {
      get { return this._expirationTimestamp != null; }
      set { if (value == (this._expirationTimestamp== null)) this._expirationTimestamp = value ? this.expirationTimestamp : (long?)null; }
    }
    private bool ShouldSerializeexpirationTimestamp() { return expirationTimestampSpecified; }
    private void ResetexpirationTimestamp() { expirationTimestampSpecified = false; }
    
    private double? _stopLossPrice;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"stopLossPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double stopLossPrice
    {
      get { return _stopLossPrice?? default(double); }
      set { _stopLossPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool stopLossPriceSpecified
    {
      get { return this._stopLossPrice != null; }
      set { if (value == (this._stopLossPrice== null)) this._stopLossPrice = value ? this.stopLossPrice : (double?)null; }
    }
    private bool ShouldSerializestopLossPrice() { return stopLossPriceSpecified; }
    private void ResetstopLossPrice() { stopLossPriceSpecified = false; }
    
    private double? _takeProfitPrice;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"takeProfitPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double takeProfitPrice
    {
      get { return _takeProfitPrice?? default(double); }
      set { _takeProfitPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool takeProfitPriceSpecified
    {
      get { return this._takeProfitPrice != null; }
      set { if (value == (this._takeProfitPrice== null)) this._takeProfitPrice = value ? this.takeProfitPrice : (double?)null; }
    }
    private bool ShouldSerializetakeProfitPrice() { return takeProfitPriceSpecified; }
    private void ResettakeProfitPrice() { takeProfitPriceSpecified = false; }
    
    private string _comment;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"comment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string comment
    {
      get { return _comment?? ""; }
      set { _comment = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool commentSpecified
    {
      get { return this._comment != null; }
      set { if (value == (this._comment== null)) this._comment = value ? this.comment : (string)null; }
    }
    private bool ShouldSerializecomment() { return commentSpecified; }
    private void Resetcomment() { commentSpecified = false; }
    
    private long? _positionId;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"positionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long positionId
    {
      get { return _positionId?? default(long); }
      set { _positionId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool positionIdSpecified
    {
      get { return this._positionId != null; }
      set { if (value == (this._positionId== null)) this._positionId = value ? this.positionId : (long?)null; }
    }
    private bool ShouldSerializepositionId() { return positionIdSpecified; }
    private void ResetpositionId() { positionIdSpecified = false; }
    
    private ProtoTimeInForce? _timeInForce;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"timeInForce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTimeInForce timeInForce
    {
      get { return _timeInForce?? ProtoTimeInForce.GOOD_TILL_DATE; }
      set { _timeInForce = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool timeInForceSpecified
    {
      get { return this._timeInForce != null; }
      set { if (value == (this._timeInForce== null)) this._timeInForce = value ? this.timeInForce : (ProtoTimeInForce?)null; }
    }
    private bool ShouldSerializetimeInForce() { return timeInForceSpecified; }
    private void ResettimeInForce() { timeInForceSpecified = false; }
    
    private string _clientOrderId;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"clientOrderId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string clientOrderId
    {
      get { return _clientOrderId?? ""; }
      set { _clientOrderId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool clientOrderIdSpecified
    {
      get { return this._clientOrderId != null; }
      set { if (value == (this._clientOrderId== null)) this._clientOrderId = value ? this.clientOrderId : (string)null; }
    }
    private bool ShouldSerializeclientOrderId() { return clientOrderIdSpecified; }
    private void ResetclientOrderId() { clientOrderIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOACancelOrderReq")]
  public partial class ProtoOACancelOrderReq : global::ProtoBuf.IExtensible
  {
    public ProtoOACancelOrderReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_CANCEL_ORDER_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private string _accessToken;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accessToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accessToken
    {
      get { return _accessToken; }
      set { _accessToken = value; }
    }
    private long _accountId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private long _orderId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"orderId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long orderId
    {
      get { return _orderId; }
      set { _orderId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAClosePositionReq")]
  public partial class ProtoOAClosePositionReq : global::ProtoBuf.IExtensible
  {
    public ProtoOAClosePositionReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_CLOSE_POSITION_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private string _accessToken;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accessToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accessToken
    {
      get { return _accessToken; }
      set { _accessToken = value; }
    }
    private long _accountId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private long _positionId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"positionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long positionId
    {
      get { return _positionId; }
      set { _positionId = value; }
    }
    private long _volume;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long volume
    {
      get { return _volume; }
      set { _volume = value; }
    }
    private ProtoTimeInForce? _timeInForce;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"timeInForce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTimeInForce timeInForce
    {
      get { return _timeInForce?? ProtoTimeInForce.GOOD_TILL_DATE; }
      set { _timeInForce = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool timeInForceSpecified
    {
      get { return this._timeInForce != null; }
      set { if (value == (this._timeInForce== null)) this._timeInForce = value ? this.timeInForce : (ProtoTimeInForce?)null; }
    }
    private bool ShouldSerializetimeInForce() { return timeInForceSpecified; }
    private void ResettimeInForce() { timeInForceSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAAmendPositionStopLossTakeProfitReq")]
  public partial class ProtoOAAmendPositionStopLossTakeProfitReq : global::ProtoBuf.IExtensible
  {
    public ProtoOAAmendPositionStopLossTakeProfitReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_AMEND_POSITION_SL_TP_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private string _accessToken;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accessToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accessToken
    {
      get { return _accessToken; }
      set { _accessToken = value; }
    }
    private long _accountId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private long _positionId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"positionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long positionId
    {
      get { return _positionId; }
      set { _positionId = value; }
    }
    private double? _stopLossPrice;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"stopLossPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double stopLossPrice
    {
      get { return _stopLossPrice?? default(double); }
      set { _stopLossPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool stopLossPriceSpecified
    {
      get { return this._stopLossPrice != null; }
      set { if (value == (this._stopLossPrice== null)) this._stopLossPrice = value ? this.stopLossPrice : (double?)null; }
    }
    private bool ShouldSerializestopLossPrice() { return stopLossPriceSpecified; }
    private void ResetstopLossPrice() { stopLossPriceSpecified = false; }
    
    private double? _takeProfitPrice;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"takeProfitPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double takeProfitPrice
    {
      get { return _takeProfitPrice?? default(double); }
      set { _takeProfitPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool takeProfitPriceSpecified
    {
      get { return this._takeProfitPrice != null; }
      set { if (value == (this._takeProfitPrice== null)) this._takeProfitPrice = value ? this.takeProfitPrice : (double?)null; }
    }
    private bool ShouldSerializetakeProfitPrice() { return takeProfitPriceSpecified; }
    private void ResettakeProfitPrice() { takeProfitPriceSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAAmendOrderReq")]
  public partial class ProtoOAAmendOrderReq : global::ProtoBuf.IExtensible
  {
    public ProtoOAAmendOrderReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_AMEND_ORDER_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private string _accessToken;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accessToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accessToken
    {
      get { return _accessToken; }
      set { _accessToken = value; }
    }
    private long _accountId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private long _orderId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"orderId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long orderId
    {
      get { return _orderId; }
      set { _orderId = value; }
    }
    private ProtoTimeInForce? _timeInForce;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"timeInForce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoTimeInForce timeInForce
    {
      get { return _timeInForce?? ProtoTimeInForce.GOOD_TILL_CANCEL; }
      set { _timeInForce = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool timeInForceSpecified
    {
      get { return this._timeInForce != null; }
      set { if (value == (this._timeInForce== null)) this._timeInForce = value ? this.timeInForce : (ProtoTimeInForce?)null; }
    }
    private bool ShouldSerializetimeInForce() { return timeInForceSpecified; }
    private void ResettimeInForce() { timeInForceSpecified = false; }
    
    private double? _limitPrice;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"limitPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double limitPrice
    {
      get { return _limitPrice?? default(double); }
      set { _limitPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool limitPriceSpecified
    {
      get { return this._limitPrice != null; }
      set { if (value == (this._limitPrice== null)) this._limitPrice = value ? this.limitPrice : (double?)null; }
    }
    private bool ShouldSerializelimitPrice() { return limitPriceSpecified; }
    private void ResetlimitPrice() { limitPriceSpecified = false; }
    
    private double? _stopPrice;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"stopPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double stopPrice
    {
      get { return _stopPrice?? default(double); }
      set { _stopPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool stopPriceSpecified
    {
      get { return this._stopPrice != null; }
      set { if (value == (this._stopPrice== null)) this._stopPrice = value ? this.stopPrice : (double?)null; }
    }
    private bool ShouldSerializestopPrice() { return stopPriceSpecified; }
    private void ResetstopPrice() { stopPriceSpecified = false; }
    
    private long? _expirationTimestamp;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"expirationTimestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long expirationTimestamp
    {
      get { return _expirationTimestamp?? default(long); }
      set { _expirationTimestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool expirationTimestampSpecified
    {
      get { return this._expirationTimestamp != null; }
      set { if (value == (this._expirationTimestamp== null)) this._expirationTimestamp = value ? this.expirationTimestamp : (long?)null; }
    }
    private bool ShouldSerializeexpirationTimestamp() { return expirationTimestampSpecified; }
    private void ResetexpirationTimestamp() { expirationTimestampSpecified = false; }
    
    private long? _minVolume;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"minVolume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long minVolume
    {
      get { return _minVolume?? default(long); }
      set { _minVolume = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool minVolumeSpecified
    {
      get { return this._minVolume != null; }
      set { if (value == (this._minVolume== null)) this._minVolume = value ? this.minVolume : (long?)null; }
    }
    private bool ShouldSerializeminVolume() { return minVolumeSpecified; }
    private void ResetminVolume() { minVolumeSpecified = false; }
    
    private double? _stopLossPrice;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"stopLossPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double stopLossPrice
    {
      get { return _stopLossPrice?? default(double); }
      set { _stopLossPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool stopLossPriceSpecified
    {
      get { return this._stopLossPrice != null; }
      set { if (value == (this._stopLossPrice== null)) this._stopLossPrice = value ? this.stopLossPrice : (double?)null; }
    }
    private bool ShouldSerializestopLossPrice() { return stopLossPriceSpecified; }
    private void ResetstopLossPrice() { stopLossPriceSpecified = false; }
    
    private double? _takeProfitPrice;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"takeProfitPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double takeProfitPrice
    {
      get { return _takeProfitPrice?? default(double); }
      set { _takeProfitPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool takeProfitPriceSpecified
    {
      get { return this._takeProfitPrice != null; }
      set { if (value == (this._takeProfitPrice== null)) this._takeProfitPrice = value ? this.takeProfitPrice : (double?)null; }
    }
    private bool ShouldSerializetakeProfitPrice() { return takeProfitPriceSpecified; }
    private void ResettakeProfitPrice() { takeProfitPriceSpecified = false; }
    
    private int? _relativeStopLossInPips;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"relativeStopLossInPips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int relativeStopLossInPips
    {
      get { return _relativeStopLossInPips?? default(int); }
      set { _relativeStopLossInPips = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool relativeStopLossInPipsSpecified
    {
      get { return this._relativeStopLossInPips != null; }
      set { if (value == (this._relativeStopLossInPips== null)) this._relativeStopLossInPips = value ? this.relativeStopLossInPips : (int?)null; }
    }
    private bool ShouldSerializerelativeStopLossInPips() { return relativeStopLossInPipsSpecified; }
    private void ResetrelativeStopLossInPips() { relativeStopLossInPipsSpecified = false; }
    
    private int? _relativeTakeProfitInPips;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"relativeTakeProfitInPips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int relativeTakeProfitInPips
    {
      get { return _relativeTakeProfitInPips?? default(int); }
      set { _relativeTakeProfitInPips = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool relativeTakeProfitInPipsSpecified
    {
      get { return this._relativeTakeProfitInPips != null; }
      set { if (value == (this._relativeTakeProfitInPips== null)) this._relativeTakeProfitInPips = value ? this.relativeTakeProfitInPips : (int?)null; }
    }
    private bool ShouldSerializerelativeTakeProfitInPips() { return relativeTakeProfitInPipsSpecified; }
    private void ResetrelativeTakeProfitInPips() { relativeTakeProfitInPipsSpecified = false; }
    
    private string _comment;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"comment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string comment
    {
      get { return _comment?? ""; }
      set { _comment = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool commentSpecified
    {
      get { return this._comment != null; }
      set { if (value == (this._comment== null)) this._comment = value ? this.comment : (string)null; }
    }
    private bool ShouldSerializecomment() { return commentSpecified; }
    private void Resetcomment() { commentSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOASubscribeForSpotsReq")]
  public partial class ProtoOASubscribeForSpotsReq : global::ProtoBuf.IExtensible
  {
    public ProtoOASubscribeForSpotsReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_SUBSCRIBE_FOR_SPOTS_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private long _accountId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private string _accessToken;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"accessToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accessToken
    {
      get { return _accessToken; }
      set { _accessToken = value; }
    }
    private string _symblolName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"symblolName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symblolName
    {
      get { return _symblolName; }
      set { _symblolName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOASubscribeForSpotsRes")]
  public partial class ProtoOASubscribeForSpotsRes : global::ProtoBuf.IExtensible
  {
    public ProtoOASubscribeForSpotsRes() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_SUBSCRIBE_FOR_SPOTS_RES; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private uint _subscriptionId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"subscriptionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint subscriptionId
    {
      get { return _subscriptionId; }
      set { _subscriptionId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAUnsubscribeFromSpotsReq")]
  public partial class ProtoOAUnsubscribeFromSpotsReq : global::ProtoBuf.IExtensible
  {
    public ProtoOAUnsubscribeFromSpotsReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_UNSUBSCRIBE_FROM_SPOTS_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private uint? _subscriptionId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"subscriptionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint subscriptionId
    {
      get { return _subscriptionId?? default(uint); }
      set { _subscriptionId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool subscriptionIdSpecified
    {
      get { return this._subscriptionId != null; }
      set { if (value == (this._subscriptionId== null)) this._subscriptionId = value ? this.subscriptionId : (uint?)null; }
    }
    private bool ShouldSerializesubscriptionId() { return subscriptionIdSpecified; }
    private void ResetsubscriptionId() { subscriptionIdSpecified = false; }
    
    private string _symblolName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"symblolName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symblolName
    {
      get { return _symblolName?? ""; }
      set { _symblolName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool symblolNameSpecified
    {
      get { return this._symblolName != null; }
      set { if (value == (this._symblolName== null)) this._symblolName = value ? this.symblolName : (string)null; }
    }
    private bool ShouldSerializesymblolName() { return symblolNameSpecified; }
    private void ResetsymblolName() { symblolNameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAUnsubscribeFromSpotsRes")]
  public partial class ProtoOAUnsubscribeFromSpotsRes : global::ProtoBuf.IExtensible
  {
    public ProtoOAUnsubscribeFromSpotsRes() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_UNSUBSCRIBE_FROM_SPOTS_RES; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAGetSpotSubscriptionReq")]
  public partial class ProtoOAGetSpotSubscriptionReq : global::ProtoBuf.IExtensible
  {
    public ProtoOAGetSpotSubscriptionReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_GET_SPOT_SUBSCRIPTION_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private uint _subscriptionId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"subscriptionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint subscriptionId
    {
      get { return _subscriptionId; }
      set { _subscriptionId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAGetSpotSubscriptionRes")]
  public partial class ProtoOAGetSpotSubscriptionRes : global::ProtoBuf.IExtensible
  {
    public ProtoOAGetSpotSubscriptionRes() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_GET_SPOT_SUBSCRIPTION_RES; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private ProtoOASpotSubscription _spotSubscription;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"spotSubscription", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoOASpotSubscription spotSubscription
    {
      get { return _spotSubscription; }
      set { _spotSubscription = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAGetAllSpotSubscriptionsReq")]
  public partial class ProtoOAGetAllSpotSubscriptionsReq : global::ProtoBuf.IExtensible
  {
    public ProtoOAGetAllSpotSubscriptionsReq() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_GET_ALL_SPOT_SUBSCRIPTIONS_REQ; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOAGetAllSpotSubscriptionsRes")]
  public partial class ProtoOAGetAllSpotSubscriptionsRes : global::ProtoBuf.IExtensible
  {
    public ProtoOAGetAllSpotSubscriptionsRes() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_GET_ALL_SPOT_SUBSCRIPTIONS_RES; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<ProtoOASpotSubscription> _spotSubscriptions = new global::System.Collections.Generic.List<ProtoOASpotSubscription>();
    [global::ProtoBuf.ProtoMember(2, Name=@"spotSubscriptions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoOASpotSubscription> spotSubscriptions
    {
      get { return _spotSubscriptions; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"ProtoOASpotEvent")]
  public partial class ProtoOASpotEvent : global::ProtoBuf.IExtensible
  {
    public ProtoOASpotEvent() {}
    
    private ProtoOAPayloadType? _payloadType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payloadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoOAPayloadType payloadType
    {
      get { return _payloadType?? ProtoOAPayloadType.OA_SPOT_EVENT; }
      set { _payloadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool payloadTypeSpecified
    {
      get { return this._payloadType != null; }
      set { if (value == (this._payloadType== null)) this._payloadType = value ? this.payloadType : (ProtoOAPayloadType?)null; }
    }
    private bool ShouldSerializepayloadType() { return payloadTypeSpecified; }
    private void ResetpayloadType() { payloadTypeSpecified = false; }
    
    private uint _subscriptionId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"subscriptionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint subscriptionId
    {
      get { return _subscriptionId; }
      set { _subscriptionId = value; }
    }
    private string _symbolName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"symbolName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbolName
    {
      get { return _symbolName; }
      set { _symbolName = value; }
    }
    private double? _bidPrice;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bidPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double bidPrice
    {
      get { return _bidPrice?? default(double); }
      set { _bidPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool bidPriceSpecified
    {
      get { return this._bidPrice != null; }
      set { if (value == (this._bidPrice== null)) this._bidPrice = value ? this.bidPrice : (double?)null; }
    }
    private bool ShouldSerializebidPrice() { return bidPriceSpecified; }
    private void ResetbidPrice() { bidPriceSpecified = false; }
    
    private double? _askPrice;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"askPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double askPrice
    {
      get { return _askPrice?? default(double); }
      set { _askPrice = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool askPriceSpecified
    {
      get { return this._askPrice != null; }
      set { if (value == (this._askPrice== null)) this._askPrice = value ? this.askPrice : (double?)null; }
    }
    private bool ShouldSerializeaskPrice() { return askPriceSpecified; }
    private void ResetaskPrice() { askPriceSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}